# Generated by Django 2.0.6 on 2018-06-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='assignedTo',
        ),
    ]
