# Generated by Django 2.0.6 on 2018-06-21 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20180621_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(default='pepe', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='typePet',
            field=models.CharField(default='dog', max_length=100),
            preserve_default=False,
        ),
    ]
