# Generated by Django 2.0.6 on 2018-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='place',
            field=models.CharField(max_length=250),
        ),
    ]
